# Generated by Django 5.2.9 on 2025-12-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('master', 'Master'), ('slave', 'Slave'), ('superuser', 'Superuser')], default='Slave', max_length=20),
        ),
    ]
