# Generated by Django 5.2.9 on 2025-12-23 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopiedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.BooleanField(default=False)),
                ('execution_price', models.FloatField(blank=True, null=True)),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.trade')),
            ],
        ),
    ]
